client_config_backend: settings
client_config:
  client_id: "" #This would be in your client_secrets.json
  client_secret: "" #This would be in your client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json #credentials should be stored in the this specific file

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive #specifies the permission or access level, in this case, for accessing Google Drive, with https://www.googleapis.com/auth/drive.